kong/version:
  runbook: "https://ensono.com"
  stages:
    - name: "dev_industrytest"
      targets:
        - resourceName: '<cluster-name>'
          resourceRegion: '<cluster-region>'
          namespace: "<kong-namespace>"