# PingIDM version check compares the running version against the latest version
# defined in the latest_versions file. The last 3 patch versions are considered up-to-date.
ping/ping_idm:
  runbook: 'http://www.ensono.com'
  stages:
    - name: 'dev'
      targets:
      - versionEndpoint: 'https://{{dev-host}}/openidm/info/version'
    - name: 'prod'
      targets:
      - versionEndpoint: 'https://{{prod-host}}/openidm/info/version'