azure/azure_application_gateway:
  runbook: 'http://www.ensono.com'
  certificateRenewalBeforeInDays: 10
  stages:
    - name: 'nonprod'
      targets:
        - resourceGroupName: '[RESOURCE GROUP NAME]'
          resourceName: '[RESOURCE NAME]'
    - name: 'prod'
      targets:
        - resourceGroupName: '[RESOURCE GROUP NAME]'
          resourceName: '[RESOURCE NAME]'
